config/routes.rb
Radspannerei::Application.routes.draw do
  
  resources :categories do
    resources :internals
  end
  

  resources :orders, :only => [:index, :show]

  resources :customers do
    resources :orders
  end

  
  

  

end

app/models/customer.rb
require 'resolv'

class Customer < ActiveRecord::Base
  has_many :orders

 
  EMAIL_PATTERN  = /(\S+)@(\S+)/
  SERVER_TIMEOUT = 3 #seconds

  validates_format_of :email, :with => EMAIL_PATTERN
  validate :validate_email




  def valid_domain?(email)
    domain = email.match(EMAIL_PATTERN)[2]
    dns    = Resolv::DNS.new

    Timeout::timeout(SERVER_TIMEOUT) do

      mx_records = dns.getresources(domain, Resolv::DNS::Resource::IN::MX)

      mx_records.sort_by{ |mx| mx.preference}.each do |mx|
        a_records = dns.getresources(mx.exchange.to_s, Resolv::DNS::Resource::IN::A)
        return true if a_records.any?
      end

      a_records = dns.getresources(domain, Resolv::DNS::Resource::IN::A)
      a_records.any?
    end
  rescue Timeout::Error, Errno::ECONNREFUSED
    false
  end


  def validate_email
    if errors[:email].empty?
      unless valid_domain?(email)
        errors.add(:email, 'Die email scheint falsch zu sein.')
      end
    end
  end

  def self.search(search, page, letter)
    search_text = letter.blank? ? "%#{search}%" : "#{letter}%"
    if(letter || search)
      paginate(:page => page, :conditions => ['lastname LIKE ?', search_text], :order => 'lastname')
    else
      paginate(:per_page => 8, :page => page, :conditions => ['lastname LIKE ?', search_text], :order => 'lastname')
    end

  end



end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # auto_complete_for :customer, :name


  # GET /customers
  # GET /customers.json
  def index
    params[:letter] = next_letter(params[:letter], params[:direction]) if params[:direction] && params[:letter]
    @customers = Customer.search(params[:search], params[:page], params[:letter])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Kunden wurde erfolgreich aufgenommen.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :ok }
    end
  end


  # returns next or previous letter of alphabet
  def next_letter letter, direction
      offset = (direction == 'foreward' ? 1 : -1) 
      ("A".."Z").to_a[(("A".."Z").to_a.index(letter) + offset) % 26]
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_alphabet.html.erb
<div id="alphabet">
  <ul>
  <% if params[:letter] %>
    <li>
      <%= link_to '<', :controller => 'customers', :action => 'index', :letter => params[:letter], :direction => 'backward' %> 
    </li>
  <% end %>
  <% ('A'..'Z').to_a.each do |letter| %>
    <li>
      <%= link_to letter, :controller => 'customers', :action => 'index', :letter => letter %>  
    </li>
  <% end %>
  <% if params[:letter] %> 
    <li> 
      <%= link_to '>', :controller => 'customers', :action => 'index', :letter => params[:letter], :direction => 'foreward' %> 
    </li>
  <% end %>
  </ul>  
</div>

app/views/customers/_customer.html.erb
<% unless just_address %>
  <p>
    <%= customer.name %>
  </p>

  <p>
    <%= customer.lastname %>
  </p>
<% end %>

<p>
  <%= customer.street %>
</p>

<p>
  <%= customer.city %>
</p>

<p>
  <%= customer.phone %>
</p>

<p>
  <%= customer.email %>
</p>

<% unless just_address %>
  <% if customer.pkunde %>
    <p>ein p-kunde</p>
  <% end %>
<% end %>

app/views/customers/_customer_table.html.erb
<table>
  <tr>
    <th><%=t :lastname, :scope => [:customer, :index] %></th>
    <th><%=t :firstname, :scope => [:customer, :index] %></th>
    <th><%=t :telefon, :scope => [:customer, :index] %></th>
    <th><%=t :email, :scope => [:customer, :index] %></th>
    <th><%=t :amount, :scope => [:customer, :index] %></th>
  </tr>

  <% @customers.each do |customer| %>
    <tr onclick="location.href='<%= customer_path customer %>'"  >
      <td><%= customer.lastname %></td>
      <td><%= customer.name %></td>
      <td><%= customer.phone %></td>
      <td><%= customer.email %></td>
      <td><%= customer.orders.size unless customer.orders.nil? %></td>
    </tr>
  <% end %>
</table>

app/views/customers/_form.html.erb
  <%= form_for(@customer) do |f| %>
    <% if @customer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

        <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <p> <%= t :contact_details, :scope => [:customer, :new] %> </p>

    <ol>
      <li>
        <%= f.label t(:lastname, :scope => [:customer, :new]) %>
        <%= f.text_field :lastname %>
      </li>
      <li>
        <%= f.label t(:firstname, :scope => [:customer, :new]) %>
        <%= f.text_field :name %>
      </li>
      <li>
      <%= f.label t(:street, :scope => [:customer, :new]) %>
        <%= f.text_field :street %>
      </li>
      <li>
        <%= f.label t(:city, :scope => [:customer, :new]) %>
        <%= f.text_field :city %>
      </li>
      <li>
        <%= f.label t(:phone, :scope => [:customer, :new]) %>
        <%= f.text_field :phone %>
      </li>
      <li>
        <%= f.label t(:email, :scope => [:customer, :new]) %>
        <%= f.text_field :email %>
      </li>
      <li>
        <%= f.label t(:p_customer, :scope => [:customer, :new]) %>
        <%= f.check_box :pkunde %>
      </li>
      <li id="send">
        <%= f.submit t(:save, :scope => [:customer, :new]), :class => 'button' %>
      </li>
    </ol>
  <% end %>

app/views/customers/_search.html.erb
<div id="search_mask">
  <%= form_tag customers_path, :method => 'get' do %>
    <div>
      <%= text_field_tag :search,  params[:search]%>
      <%= submit_tag t(:search, :scope => [:customer, :index]), :id => 'searchsubmit', :name => nil %>
    </div>
    <p><%=t :search_term, :scope => [:customer, :index] %></p>
  <% end %>
</div>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<div class="sheet">
  <div class="sheet-bgtop">
    <div class="sheet-bgbtm">

    <h1><%=t :customer, :scope => [:customer, :index] %></h1>

      <%= render :partial => 'search' %>

      <div id="results">
        <% if @customers.empty? %>
          <p>
            <%=t :found_no_customers, :scope => [:customer, :index] %> 
          </p>
        <% else %>
          <% if params[:search] %>
            <p>
              <%=t :search_results, :scope => [:customer, :index] %> 
              <span id="search"> <%= params[:search] %> </span>
            </p>
          <% else %>
            <% if params[:letter] %>
              <p>
                <%=t :first_letter, :scope => [:customer, :index] %> 
                <span id="search"> <%= params[:letter] %> </span>
              </p>
            <% end %>
          <% end %> 
        <% end %>
      </div>

      <div id = 'customer_table'>
        <%= render :partial => 'customer_table', :locals => {:customers => @customers} %>

        <div id="new_customer">
          <%= button_to t(:new_customer, :scope => [:customer, :index]), new_customer_path, :method => :get%>
        </div>
        <div id=paginate_customers>
          <%= will_paginate @customers, :page_links => false %> 
        </div>
      </div>

      <%= render :partial => 'alphabet' %>
      
    </div>
  </div>
</div>

app/views/customers/index.js.coffee.erb
$("#customers_table").html("<%= escape_javascript(render :partial => 'customer_table', :locals => {:customers => @customers} ))

app/views/customers/new.html.erb
<div class="sheet">
  <div class="sheet-bgtop">
    <div class="sheet-bgbtm">

    <div id="new_customer">

      <div id="left_side"> 
        <h1><%=t :new_customer, :scope => [:customer, :new] %> </h1>
      </div>
      <div id="right_side">
        <%= render 'form' %>
      </div>

    </div>

    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="sheet">
  <div class="sheet-bgtop">
    <div class="sheet-bgbtm">

      <div id="customer_show">

        <p id="notice"><%= notice %></p>

        <h1><%="#{@customer.name} #{@customer.lastname}:"%></h1>
          
        <div id="address">
          <%= render :partial => 'customer', :locals => {:customer => @customer, :just_address => true} %>
          <%= link_to t(:edit, :scope => [:customer, :show]), edit_customer_path(@customer) %> 
        </div>

        <div id="new_order">
          <%@order = Order.new%>
          <ol>
            <%= form_for [@customer, @order] do |f| %>
              <p><%= t(:add_new_order, :scope => [:customer, :show]) %></p> </br>
              <li>
                <%=f.label t(:article, :scope => [:customer, :show]) %>
                <%= f.text_field :article %>
              </li>
              <li>
                <%=f.label t(:number, :scope => [:customer, :show]) %>
                <%= f.text_field :order_number %>
              </li>
              <li>
                <%=f.label t(:amount, :scope => [:customer, :show]) %>
                <%= f.text_field :amount %>
              </li>
              <li>
                <%=f.label t(:sign, :scope => [:customer, :show]) %>
                <%= f.text_field :filledin_by %>
              </li>
              <li>
                <%=f.label t(:note, :scope => [:customer, :show]) %>
                <%= f.text_area :note %>
              </li>
              <li>
                <%=f.label t(:delivery, :scope => [:customer, :show]) %>
                <%= f.text_field :deliveryman %>
              </li>
              <li id="send">
                <%= f.submit t(:add_order, :scope => [:customer, :show]), :class => 'button' %>
              </li>

            <% end %>
          <ol>
        </div>

        <div id="customer_orders">
          <h2><%= t(:customer_orders, :scope => [:customer, :show]) %><h2>  
            <div id = 'orders_table'>
              <table>
                <tr>
                  <th><%= t(:article, :scope => [:customer, :show]) %></th>
                  <th><%= t(:status, :scope => [:customer, :show]) %></th>
                </tr>

                <% @customer.orders.each do |order| %>
                  <tr onclick="location.href='<%= order_path order %>'"  >
                    <td><%= order.article %></td>
                    <td><%= order.status_as_string %></td>
                  </tr>
                <% end %>
            </table>
            </div>
        </div>

      </div>
    </div>
  </div>
</div>