config/routes.rb
Radspannerei::Application.routes.draw do
  
  resources :categories do
    resources :internals
  end
  

  resources :orders, :only => [:index, :show]

  resources :customers do
    resources :orders
  end

  
  

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  #include OrderExtensions::Scopes
  belongs_to :customer
  #validates_article :article
  #
  STATES = [I18n.t(:unprocessed, :scope => [:order, :model, :states]), 
            I18n.t(:ordered, :scope => [:order, :model, :states]),
            I18n.t(:arrived, :scope => [:order, :model, :states]),  
            I18n.t(:picked_up, :scope => [:order, :model, :states]), 
            I18n.t(:undefined, :scope => [:order, :model, :states])]

  def status_as_string
    puts status
    case self.status
      when 1 
        STATES[0]
      when 2
        STATES[1]
      when 3
        STATES[2]
      when 4
        STATES[3]
      else
        STATES[4]
    end
  end

  def self.search(search, page, status)
    if status && search.empty?
      return paginate(:per_page => 10, :page => page, :conditions => ['status = ?', status], :order => 'article')
    end
    if !status
      return paginate(:per_page => 10, :page => page, :conditions => ['status = ?', 0], :order => 'article')    
    end
    if !search.empty?
      return paginate(:conditions => ['article LIKE ? and status = ?', search, status], :order => 'article', :page => page)
    end 
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
   # params[:sate] =  if params[:direction] && params[:letter]
    @orders = Order.search(params[:search], params[:page], params[:status])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :ok }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article %><br />
    <%= f.text_field :article %>
  </div>
  <div class="field">
    <%= f.label :order_number %><br />
    <%= f.text_field :order_number %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :deliveryman %><br />
    <%= f.text_field :deliveryman %>
  </div>
  <div class="field">
    <%= f.label :filledin_by %><br />
    <%= f.text_field :filledin_by %>
  </div>
  <div class="field">
    <%= f.label :ordered_date %><br />
    <%= f.datetime_select :ordered_date %>
  </div>
  <div class="field">
    <%= f.label :arrived_date %><br />
    <%= f.datetime_select :arrived_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="sheet">
  <div class="sheet-bgtop">
    <div class="sheet-bgbtm">

      <h1>Bestellungen:</h1>

      <div id="search_mask">
        <%= form_tag orders_path, :id => "search_form", :method => 'get' do %>
          <div>
            <%= select_tag(:status,  options_for_select(Order::STATES.collect {|v,i| [v, Order::STATES.index(v)] }, :selected => params[:status]), :onchange => 'document.forms[0].submit()') %>
            <%= text_field_tag :search,  params[:search]%>
            <%= submit_tag "Go", :id => 'searchsubmit', :name => nil %>
          </div>
          <p> (Suchen nach: Artikelname) </p>
        <% end %>
      </div>

      
      <div id="results">
        <% if @orders.empty? %>
          <p>
            Keine Bestellungen gefunden. 
          </p>
        <% else %>
          <p>
            Suchergebnisse für: 
            <span id="search"> <%= params[:search] %> </span>
          </p>
        <% end %> 
      </div>

      <div id = 'customer_table'>

        <table>
          <tr>
            <th>Artikel</th>
            <th>Anzahl</th>
            <th>Grosshaendler</th>
            <th>Status</th>
          </tr>

          <% @orders.each do |order| %>
            <tr onclick="location.href='<%= order_path order %>'" >
              <td><%= order.article %></td>
              <td><%= order.amount %></td>
              <td><%= order.deliveryman %></td>
              <td><%= order.status_as_string %></td>
            </tr>
          <% end %>
        </table>

        <div id=paginate_customers>
          <%= will_paginate @orders %> 
        </div>
      </div>
    </div>
  </div>
</div>




<br />

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Article:</b>
  <%= @order.article %>
</p>

<p>
  <b>Order number:</b>
  <%= @order.order_number %>
</p>

<p>
  <b>Note:</b>
  <%= @order.note %>
</p>

<p>
  <b>Amount:</b>
  <%= @order.amount %>
</p>

<p>
  <b>Deliveryman:</b>
  <%= @order.deliveryman %>
</p>

<p>
  <b>Filledin by:</b>
  <%= @order.filledin_by %>
</p>

<p>
  <b>Ordered date:</b>
  <%= @order.ordered_date %>
</p>

<p>
  <b>Arrived date:</b>
  <%= @order.arrived_date %>
</p>


<%= link_to 'Back', orders_path %>