config/routes.rb
Radspannerei::Application.routes.draw do
  
  resources :categories do
    resources :internals
  end
  

  resources :orders, :only => [:index, :show]

  resources :customers do
    resources :orders
  end

  
  

  

end

app/models/internal.rb
class Internal < ActiveRecord::Base
  belongs_to :category
  validates_article :article

  STATES = [I18n.t(:unprocessed, :scope => [:order, :model, :states]), 
            I18n.t(:ordered, :scope => [:order, :model, :states]),
            I18n.t(:arrived, :scope => [:order, :model, :states]),  
            I18n.t(:picked_up, :scope => [:order, :model, :states]), 
            I18n.t(:undefined, :scope => [:order, :model, :states])]

  def status_as_string
    case self.status
      when 1 
        STATES[0]
      when 2
        STATES[1]
      when 3
        STATES[2]
      when 4
        STATES[3]
      else
        STATES[4]
    end
  end

  def self.search(search, page, status)
  #  if status && search.empty?
  #    return paginate(:per_page => 10, :page => page, :conditions => ['status = ?', status], :order => 'article')
  #  end
  #  if !status
  #    return paginate(:per_page => 10, :page => page, :conditions => ['status = ?', 0], :order => 'article')    
  #  end
  #  if !search.empty?
  #    return paginate(:conditions => ['article LIKE ? and status = ?', search, status], :order => 'article', :page => page)
  #  end 
  end

end

app/controllers/internals_controller.rb
class InternalsController < ApplicationController

  before_filter :find_category

  # GET /internals
  # GET /internals.json
  def index
    @internals = Internal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @internals }
    end
  end

  # GET /internals/1
  # GET /internals/1.json
  def show

    @internal = Internal.find(params[:id])

    puts @internal.inspect

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @internal }
    end
  end

  # GET /internals/new
  # GET /internals/new.json
  def new
    puts @category.inspect
    @internal = @category.internals.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @internal }
    end
  end

  # GET /internals/1/edit
  def edit
    @internal = Internal.find(params[:id])
  end

  # POST /internals
  # POST /internals.json
  def create
    #category = Category.find(params[:category_id])
    @internal = Internal.new(params[:internal])
    @category.internals << @internal

    respond_to do |format|
      if @internal.save
        format.html { redirect_to category_path(@category), notice: 'Internal was successfully created.' }
        format.json { render json: @internal, status: :created, location: @internal }
      else
        format.html { render action: "new" }
        format.json { render json: @internal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /internals/1
  # PUT /internals/1.json
  def update
    @internal = Internal.find(params[:id])

    respond_to do |format|
      if @internal.update_attributes(params[:internal])
        format.html { redirect_to category_internal_path(@category, @internal), notice: 'Internal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @internal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /internals/1
  # DELETE /internals/1.json
  def destroy
    @internal = Internal.find(params[:id])
    @internal.destroy

    respond_to do |format|
      format.html { redirect_to internals_url }
      format.json { head :ok }
    end
  end


  private
  
  def find_category
    @category = Category.find(params[:category_id])
  end

end

app/helpers/internals_helper.rb
module InternalsHelper
end

app/views/internals/_form.html.erb
<%= form_for([@category, @internal]) do |f| %>
  <% if @internal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@internal.errors.count, "error") %> prohibited this internal from being saved:</h2>

      <ul>
      <% @internal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article %><br />
    <%= f.text_field :article %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= select_tag 'category_id', options_for_select(nested_set_options(Category) {|i| "#{'-' * i.level} #{i.name}" } ) %>
    </div>
  <div class="field">
    <%= f.label :order_number %><br />
    <%= f.text_field :order_number %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :deliveryman %><br />
    <%= f.text_field :deliveryman %>
  </div>
  <div class="field">
    <%= f.label :filledin_by %><br />
    <%= f.text_field :filledin_by %>
  </div>
  <div class="field">
    <%= f.label :order_arrived %><br />
    <%= f.datetime_select :order_arrived %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/internals/edit.html.erb
<h1>Editing internal</h1>

<%= render 'form' %>

<%= link_to 'Show', category_internal_path(@category, @internal) %> |
<%= link_to 'Back', category_internals_path %>

app/views/internals/index.html.erb
<h1>Listing internals</h1>

<table>
  <tr>
    <th>Article</th>
    <th>Order number</th>
    <th>Note</th>
    <th>Amount</th>
    <th>Deliveryman</th>
    <th>Filledin by</th>
    <th>Order arrived</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @internals.each do |internal| %>
  <tr>
    <td><%= internal.article %></td>
    <td><%= internal.order_number %></td>
    <td><%= internal.note %></td>
    <td><%= internal.amount %></td>
    <td><%= internal.deliveryman %></td>
    <td><%= internal.filledin_by %></td>
    <td><%= internal.order_arrived %></td>
    <td><%= link_to 'Show', internal %></td>
    <td><%= link_to 'Edit', edit_category_internal_path(internal) %></td>
    <td><%= link_to 'Destroy', internal, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Internal', new_category_internal_path %>

app/views/internals/new.html.erb
<h1>New internal</h1>

<%= render 'form' %>

<%= link_to 'Back', category_internals_path %>

app/views/internals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Article:</b>
  <%= @internal.article %>
</p>

<p>
  <b>Order number:</b>
  <%= @internal.order_number %>
</p>

<p>
  <b>Note:</b>
  <%= @internal.note %>
</p>

<p>
  <b>Amount:</b>
  <%= @internal.amount %>
</p>

<p>
  <b>Deliveryman:</b>
  <%= @internal.deliveryman %>
</p>

<p>
  <b>Filledin by:</b>
  <%= @internal.filledin_by %>
</p>

<p>
  <b>Order arrived:</b>
  <%= @internal.order_arrived %>
</p>


<%= link_to 'Edit', edit_category_internal_path(@internal) %> |
<%= link_to 'Back', category_internals_path %>