config/routes.rb
Radspannerei::Application.routes.draw do
  
  resources :categories do
    resources :internals
  end
  

  resources :orders, :only => [:index, :show]

  resources :customers do
    resources :orders
  end

  
  

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set
  attr_accessible :name, :parent_id
  has_many :internals

  def all_internals
    self_and_descendants.map{ |x| x.internals }.flatten
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # GET /categories
  # GET /categories.json
  
  respond_to :html, :js

  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category  = Category.find(params[:id])
    @internals = @category.all_internals

    @internals.each do |i|
      puts i.inspect
    end

    #respond_with @category, :location => category_url

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category, :location => category_url }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<li>

<% if links %>
  <%= link_to category.name, category_path(category.id), :method => :get, :remote => true%>
<% else %>
  <%= link_to(category.name, category_path(category)) %>
<% end %>

<% if category.children.exists? %>
  <ul>
    <% category.children.each do |child| %>
      <%= render :partial => "category", :locals => { :category => child, :links => links  } %>
    <% end %>
  </ul>
<% end %>

</li>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Oberkategorie" %><br />
    <%= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" }.unshift(["oberste Kategorie", nil]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_items.html.erb
<table>
  <tr>
    <th>Artikel</th>
    <th>Grosshaendler</th>
    <th>Anzahl</th>
    <th>Status</th>
  </tr>

  <% @internals.each do |internal| %>
    <tr onclick="location.href='<%= category_internal_path(@category, internal) %>'"  >
      <td><%= internal.article %></td>
      <td><%= internal.deliveryman%></td>
      <td><%= internal.amount%></td>
      <td><%= internal.status_as_string%></td>
    </tr>
  <% end %>
</table>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% content_for :categories do %>

  <div class="sheet">
    <div class="sheet-bgtop">
      <div class="sheet-bgbtm">

        <div id="categories_list">
          <h1>Kategorien verwalten</h1>
          <table>
            <tr>
              <th>Name</th>
              <th>Oberkategorie</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>

            <% @categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td><%= category.parent ? category.parent.name : "hoechste Kategorie" %></td>
                <td><%= link_to 'Bestellungen', category %></td>
                <td><%= link_to 'Veraendern', edit_category_path(category) %></td>
                <td><%= link_to 'Loeschen', category, confirm: 'Are you sure?', method: :delete %></td>
              </tr>
            <% end %>
          </table>

        </div>


        <div id="listContainer">
          <h1>Kategorien</h1>
          <ul id="expList">
            <% Category.roots.each do |category| %>
              <%= render :partial => "category", :locals => { :category => category, :links => true } %>
            <% end %>
          </ul>
        </div>

      </div>

    </div>

  </div>

<% end %>

     

app/views/categories/new.html.erb
<h1>Neue Kategorie</h1>

<div id="listContainer">
  <ul id="expList">
    <% Category.roots.each do |category| %>
      <%= render :partial => "category", :locals => { :category => category, :links => false} %>
    <% end %>
  </ul>
</div>

<%= render 'form' %>

<%= link_to 'Zurück', categories_path %>

app/views/categories/show.html.erb
<% content_for :categories do %>

  <div class="sheet">
    <div class="sheet-bgtop">
      <div class="sheet-bgbtm">

        <div id="categories_menu">
          <h1>Kategorien</h1>
          <ul id="expList">
            <% Category.roots.each do |category| %>
              <%= render :partial => "category", :locals => { :category => category, :links => false } %>
            <% end %>
          </ul>
        </div>

        <p id="notice"><%= notice %></p>

        <div id="items">
          <h1>Interne Bestellungen</h1>
          <p>
            Kategorien:
            <% @category.self_and_ancestors.each_with_index do |ancester, i| %>
              <% unless i == 0 %>
                ->
              <% end %>
              <%= ancester.name %>  
            <% end %>
          </p>
          <%= render :partial => 'items' %>
        </div>

        <div id="">
          <%=link_to "Neue Bestellung", new_category_internal_path(@category) %>
        </div>

      </div>
    </div>
  </div>

 <% end %>

app/views/categories/show.js.erb
alert("hallo");

$("#items").html('<%= escape_javascript( render :partial => 'items', :locals => { :items => @category.internals } ) %>')